# Generated by Django 4.2.7 on 2023-11-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_rename_foreign_habit_habit_other_habit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='other_habit',
            new_name='foreign_habit',
        ),
    ]
